### ISSUE TITLE
Make location of wof_cache folders configurable

### ISSUE THREAD

**Issue by otbutz** [pelias/polylines#146]
I'm currently working on a dockerized Pelias instance and want to keep the root filesystem readonly. Being able to specify a location for the following folders is the missing piece of the puzzle:

```
/opt/pelias/polylines/wof_cache11825-456-i9ilu1.n321z9qkt9
/opt/pelias/polylines/wof_cache11825-456-i9ilu1.n321z9qkt9/wof-neighbourhood-data.json
/opt/pelias/polylines/wof_cache11825-462-c3qw0u.n9eo28olxr
/opt/pelias/polylines/wof_cache11825-462-c3qw0u.n9eo28olxr/wof-borough-data.json
/opt/pelias/polylines/wof_cache11825-465-9oe7kb.cimkakyb9
/opt/pelias/polylines/wof_cache11825-465-9oe7kb.cimkakyb9/wof-locality-data.json
/opt/pelias/polylines/wof_cache11825-469-1di150f.bm5qfo5hfr
/opt/pelias/polylines/wof_cache11825-469-1di150f.bm5qfo5hfr/wof-localadmin-data.json
/opt/pelias/polylines/wof_cache11825-480-ovvpxj.1eio8t1emi
/opt/pelias/polylines/wof_cache11825-480-ovvpxj.1eio8t1emi/wof-county-data.json
/opt/pelias/polylines/wof_cache11825-486-1ooyi7i.33srf3whfr
/opt/pelias/polylines/wof_cache11825-486-1ooyi7i.33srf3whfr/wof-macrocounty-data.json
/opt/pelias/polylines/wof_cache11825-492-1aenzb4.ax0024vx6r
/opt/pelias/polylines/wof_cache11825-492-1aenzb4.ax0024vx6r/wof-macroregion-data.json
/opt/pelias/polylines/wof_cache11825-498-1jt41eg.zbh3cmobt9
/opt/pelias/polylines/wof_cache11825-498-1jt41eg.zbh3cmobt9/wof-region-data.json
/opt/pelias/polylines/wof_cache11825-499-cwmq4e.ztpflmcxr
/opt/pelias/polylines/wof_cache11825-499-cwmq4e.ztpflmcxr/wof-dependency-data.json
/opt/pelias/polylines/wof_cache11825-505-1z0mlnr.21mwfp3nmi
/opt/pelias/polylines/wof_cache11825-505-1z0mlnr.21mwfp3nmi/wof-country-data.json
/opt/pelias/polylines/wof_cache11825-506-1ngfoq7.ebo6klc8fr
/opt/pelias/polylines/wof_cache11825-506-1ngfoq7.ebo6klc8fr/wof-empire-data.json
/opt/pelias/polylines/wof_cache11825-522-2ui1a9.tv21uac3di
/opt/pelias/polylines/wof_cache11825-522-2ui1a9.tv21uac3di/wof-continent-data.json
/opt/pelias/polylines/wof_cache11825-523-c46q62.4c28x5hfr
/opt/pelias/polylines/wof_cache11825-523-c46q62.4c28x5hfr/wof-marinearea-data.json
/opt/pelias/polylines/wof_cache11825-529-si5oz9.u0ytoi529
/opt/pelias/polylines/wof_cache11825-529-si5oz9.u0ytoi529/wof-ocean-data.json
```
(production branch; adminLookup enabled; import started with `cd /opt/pelias/polylines && npm start`)

**Comment by missinglink** [comment]
hi @otbutz I'm not following you, is this a bug?

**Comment by otbutz** [comment]
No, just a feature request. It would be nice if the location of the cache folders could be configured via `pelias.json`

**Comment by orangejulius** [comment]
I would consider this a minor performance/security bug. It's often the case that writes to the root FS of a docker container are slower than to a mounted volume. And in any case writing to the container's root FS violates the premise that the container never changes. In this case it's merely an annoyance but in general it's good to avoid.

Grepping through the code, I realized these files actually come from [wof-admin-lookup](https://github.com/pelias/wof-admin-lookup/blob/master/src/pip/worker.js#L36). In the near future we'll make default a configuration where those files won't ever be generated in this container, so the immediate problem will be fixed.

In the longer term we'll also probably change the architecture of the [pip-service](https://github.com/pelias/pip-service) which uses those files so that they're no longer generated at all.

**Comment by orangejulius** [comment]
Hello @otbutz,
Long time no talk, but if you are interested, we have just merged a change inhttps://github.com/pelias/wof-admin-lookup/pull/231 that stops these files from being generated all together. The Pelias dockerfiles will be updated in the next few hours and then all should be well.

We are embarking on a journey to enforce read-only root filesystems for all Pelias containers, which you attempted long ago. If you'd like, please report on any other areas that cause/caused you trouble in https://github.com/pelias/pelias/issues/745. Thanks!
