### ISSUE TITLE
how can I open file extract.0sv / .polylines???

### ISSUE THREAD

**Issue by stefanocudini** [pelias/polylines#218]
I don't understand what kind of format this file is and how I can visualize it to make a test of the contained geometry

many tnks

**Comment by missinglink** [comment]
The polylines file format (also known as `.0sv`) consists of an encoded polyline string as per https://developers.google.com/maps/documentation/utilities/polylinealgorithm with the exception of using a precision of 6 instead of 5 shown in that example.

The encoded polyline is then followed by a null byte and then the street name as a UTF8 encoded string.
Each line is delimited by a newline.

You can use this demo to decode the polyline: http://valhalla.github.io/demos/polyline/
Note: you may need to remove the street name segment to get correct results using the demo
